//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.28 at 08:10:57 PM MSK 
//


package by.training.news.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Name.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Name">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="films"/>
 *     &lt;enumeration value="disks"/>
 *     &lt;enumeration value="books"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Name")
@XmlEnum
public enum Name {

    @XmlEnumValue("films")
    FILMS("films"),
    @XmlEnumValue("disks")
    DISKS("disks"),
    @XmlEnumValue("books")
    BOOKS("books");
    private final String value;

    Name(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Name fromValue(String v) {
        for (Name c: Name.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
