//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.28 at 08:10:57 PM MSK 
//


package by.training.news.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for News complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="News">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="news-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provider" type="{http://www.training.by/news}Provider"/>
 *         &lt;element name="data-of_issue" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="news-body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "News", propOrder = {
    "newsName",
    "provider",
    "dataOfIssue",
    "newsBody"
})
public class News {

    @XmlElement(name = "news-name", required = true)
    protected String newsName;
    @XmlElement(required = true)
    protected Provider provider;
    @XmlElement(name = "data-of_issue", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataOfIssue;
    @XmlElement(name = "news-body", required = true)
    protected String newsBody;

    /**
     * Gets the value of the newsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsName() {
        return newsName;
    }

    /**
     * Sets the value of the newsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsName(String value) {
        this.newsName = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link Provider }
     *     
     */
    public Provider getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Provider }
     *     
     */
    public void setProvider(Provider value) {
        this.provider = value;
    }

    /**
     * Gets the value of the dataOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataOfIssue() {
        return dataOfIssue;
    }

    /**
     * Sets the value of the dataOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataOfIssue(XMLGregorianCalendar value) {
        this.dataOfIssue = value;
    }

    /**
     * Gets the value of the newsBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsBody() {
        return newsBody;
    }

    /**
     * Sets the value of the newsBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsBody(String value) {
        this.newsBody = value;
    }    
    
	@Override
	public String toString() {
		return "News [newsName=" + newsName + ", \r\nprovider=" + provider 
				+ ",\r\n dataOfIssue=" + dataOfIssue 
				+ ", \r\nnewsBody="+ newsBody + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dataOfIssue == null) ? 0 : dataOfIssue.hashCode());
		result = prime * result + ((newsBody == null) ? 0 : newsBody.hashCode());
		result = prime * result + ((newsName == null) ? 0 : newsName.hashCode());
		result = prime * result + ((provider == null) ? 0 : provider.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		News other = (News) obj;
		if (dataOfIssue == null) {
			if (other.dataOfIssue != null)
				return false;
		} else if (!dataOfIssue.equals(other.dataOfIssue))
			return false;
		if (newsBody == null) {
			if (other.newsBody != null)
				return false;
		} else if (!newsBody.equals(other.newsBody))
			return false;
		if (newsName == null) {
			if (other.newsName != null)
				return false;
		} else if (!newsName.equals(other.newsName))
			return false;
		if (provider == null) {
			if (other.provider != null)
				return false;
		} else if (!provider.equals(other.provider))
			return false;
		return true;
	}
    
}
